TEAM_MAP = {
    "Real Madrid": "real_madrid",
    "Barcelona": "barcelona",
    "Atlético Madrid": "atletico_madrid",
    "Sevilla": "sevilla",
    "Valencia": "valencia",
    "Alavés": "alaves",
    "Real Betis": "real_betis",
    "Real Oviedo": "oviiedo",
    "Real Sociedad": "real_sociedad",
    "Villarreal": "villarreal",
    "Arsenal": "arsenal",
    "Aston Villa": "aston_villa",
    "Bournemouth": "bournemouth",
    "Brentford": "brentford",
    "Brighton": "brighton",
    "Burnley": "burnley",
    "Chelsea": "chelsea",
    "Crystal Palace": "crystal_palace",
    "Everton": "everton",
    "Fulham": "fullham",
    "Liverpool": "liverpool",
    "Manchester City": "manchester_city",
    "Manchester United": "manchester_united",
    "Newcastle United": "newcastle",
    "Nottingham Forest": "nottingham_forest",
    "Tottenham": "tottenham",
    "West Ham": "west_ham",
    "Wolverhampton Wanderers": "wolverhampton",
    "Bayern Munich": "bayern_munich",
    "Borussia Dortmund": "dortmund",
    "RB Leipzig": "leipzig",
    "Bayer Leverkusen": "bayer_leverkusen",
    "Eintracht Frankfurt": "eintracht_frankfurt",
    "Stuttgart": "stuttgart",
    "Borussia Mönchengladbach": "monchengladbach",
    "Werder Bremen": "werder_bremen",
    "Hoffenheim": "hoffenheim",
    "Freiburg": "freiburg",
    "Juventus": "juventus",
    "Inter Milan": "inter",
    "AC Milan": "milan",
    "Napoli": "napoli",
    "Roma": "roma",
    "Atalanta": "atalanta",
    "Lazio": "lazio",
    "Fiorentina": "fiorentina",
    "Bologna": "bologna",
    "Torino": "torino",
    "Genoa": "genoa",
    "Espanyol": "espanyol",
    "Getafe": "getafe",
    "Athletic Club": "athletic_club",
    "Rayo Vallecano": "rayo_vallecano",
    "Elche": "elche",
    "Celta Vigo": "celta_vigo",
    "Mallorca": "mallorca",
    "Osasuna": "osasuna",
    "Girona": "girona",
    "Levante": "levante",
    "Sunderland": "sunderland",
    "Leeds United": "leeds_united",
    "Udinese": "udinese",
    "Sassuolo": "sassuolo",
    "Cremonese": "cremonese",
    "Lecce": "lecce",
    "Cagliari": "cagliari",
    "Parma": "parma",
    "Pisa": "pisa",
    "Hellas Verona": "hellas_verona",
    "Köln": "koln",
    "Union Berlin": "union_berlin",
    "Hamburg": "hamburg",
    "Augsburg": "augsburg",
    "Wolfsburg": "wolfsburg",
    "Heidenheim": "heidenheim",
    "St. Pauli": "stpauli",
    "Mainz": "mainz",
    "Como": "como",
    "Ajax": "ajax",
    "Benfica": "benfica",
    "Bodo/Glimt": "bodo_glimt",
    "Club Brugge": "club_brujas",
    "Dortmund": "dortmund",
    "FC Copenhagen": "copenhagen",
    "Frankfurt": "frankfurt",
    "Galatasaray": "galatasaray",
    "Leverkusen": "bayer_leverkusen",
    "Man City": "manchester_city",
    "Marseille": "marseille",
    "Monaco": "monaco",
    "Newcastle": "newcastle",
    "Olympiacos": "olympiacos",
    "PSG": "psg",
    "PSV": "psv",
    "Qarabag FK": "qarabag_fk",
    "Slavia Prague": "slavia_prague",
    "Sporting": "sporting",
    "Union S-G": "union_sg"
}

def normalize_team_name(team_name: str) -> str:
    team_name = team_name.strip()
    return TEAM_MAP.get(team_name, team_name)
